### PR TITLE
Added nt_term_identifier extraction & indexing.

### PR DESCRIPTION
**Pull request by dkrylovsb**

### CODE REVIEW

**Comment by dkrylovsb** [comment]
@michael-balint , looks OK?

**Comment by michael-balint** [comment]
Looks good in terms of adding this new field - are you also working to fix the biomarker name-splitting issue?

**Comment by dkrylovsb** [comment]
Yes, I'll submit a separate pull for that one.

**Comment by michael-balint** [comment]
Ah, my bad, I meant to rebase/merge, but github's new interface update confused me.

**Pull request merged**
